server:
  port: 8760                    # 指定该Eureka实例的端口

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 20000   # 清理间隔（单位毫秒，默认是60*1000）

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

